export const HOSPITAL = {
  nameEn: "Khon Kaen Hospital",
  
  code: "KKH",
  dept: "AI Diagnostics Centre — Radiology · Hepatology · Pathology",
};

// Demo reference patients (used by Dashboard quick-launch buttons)
const DEMO_PATIENTS = [
  {
    id: "REF-AXIA-001",
    name: "Somchai Jaidee (Demo)",
    nameEn: "Somchai Jaidee (Demo)",
    age: 67, gender: "M",
    status: "Demo", priority: "Critical",
    date: "2026-06-11 08:14",
    tools: ["AXIA"],
    accession: "DEMO-CT-001",
    indication: "Sudden headache, right-sided weakness",
    ward: "Emergency Dept.",
    referrer: "Dr. Wirut Sombat",
    lastResult: null,
  },
  {
    id: "REF-LIVA-001",
    name: "Pornchai Srisuk (Demo)",
    nameEn: "Pornchai Srisuk (Demo)",
    age: 52, gender: "M",
    status: "Demo", priority: "Urgent",
    date: "2026-06-11 09:45",
    tools: ["SmartLiva"],
    accession: "DEMO-US-001",
    indication: "Chronic HBV, 3-year follow-up liver US",
    ward: "Hepatology OPD",
    referrer: "Dr. Siriporn Maneerat",
    lastResult: null,
  },
  {
    id: "REF-PICHA-001",
    name: "Prayoon Chaidee (Demo)",
    nameEn: "Prayoon Chaidee (Demo)",
    age: 58, gender: "M",
    status: "Demo", priority: "Urgent",
    date: "2026-06-11 08:30",
    tools: ["PICHA"],
    accession: "DEMO-PATH-001",
    indication: "Liver biopsy — suspect CCA, OV-endemic background",
    ward: "Hepatobiliary Surgery",
    referrer: "Dr. Wanchai Uttaraphol",
    lastResult: null,
  },
];

export const MOCK_PATIENTS = [
  // AXIA – Brain CT
  {
    id: "HN-2566-4891",
    name: "Somchai Jaidee",
    nameEn: "Somchai Jaidee",
    age: 67, gender: "M",
    status: "Pending", priority: "Critical",
    date: "2026-06-11 08:14",
    tools: ["AXIA"],
    accession: "KKH-CT-2026-0891",
    indication: "Sudden headache, right-sided weakness",
    ward: "Emergency Dept.",
    referrer: "Dr. Wirut Sombat",
    lastResult: null,
  },
  {
    id: "HN-2566-3204",
    name: "Panita Meesuk",
    nameEn: "Panita Meesuk",
    age: 54, gender: "F",
    status: "Pending", priority: "Stat",
    date: "2026-06-11 09:02",
    tools: ["AXIA"],
    accession: "KKH-CT-2026-0892",
    indication: "Head trauma, GCS 14 after fall",
    ward: "Neurology Ward 3",
    referrer: "Dr. Porntip Saengthong",
    lastResult: null,
  },
  {
    id: "HN-2566-7741",
    name: "Wira Khayanди",
    nameEn: "Wira Khayanди",
    age: 45, gender: "M",
    status: "Reviewed", priority: "Routine",
    date: "2026-06-10 15:30",
    tools: ["AXIA"],
    accession: "KKH-CT-2026-0879",
    indication: "Post-op CT brain follow-up",
    ward: "Neurosurgery",
    referrer: "Dr. Kasem Phuthai",
    lastResult: "ICH: Negative. No midline shift detected.",
  },
  // SmartLiva – Liver US
  {
    id: "HN-2566-5512",
    name: "Pornchai Srisuk",
    nameEn: "Pornchai Srisuk",
    age: 52, gender: "M",
    status: "In Progress", priority: "Urgent",
    date: "2026-06-11 09:45",
    tools: ["SmartLiva"],
    accession: "KKH-US-2026-1120",
    indication: "Chronic HBV, 3-year follow-up liver US",
    ward: "Hepatology OPD",
    referrer: "Dr. Siriporn Maneerat",
    lastResult: null,
  },
  {
    id: "HN-2566-2089",
    name: "Malee Phetdee",
    nameEn: "Malee Phetdee",
    age: 38, gender: "F",
    status: "Pending", priority: "Urgent",
    date: "2026-06-11 10:20",
    tools: ["SmartLiva"],
    accession: "KKH-US-2026-1121",
    indication: "Elevated ALT 3× ULN, rule out fibrosis",
    ward: "Internal Medicine Ward 2",
    referrer: "Dr. Nuttapong Chaiyarat",
    lastResult: null,
  },
  {
    id: "HN-2566-8830",
    name: "Surachai Saengthong",
    nameEn: "Surachai Saengthong",
    age: 61, gender: "M",
    status: "Reviewed", priority: "Routine",
    date: "2026-06-10 11:00",
    tools: ["SmartLiva"],
    accession: "KKH-US-2026-1105",
    indication: "Annual US monitoring, known liver cirrhosis F3",
    ward: "Hepatology OPD",
    referrer: "Dr. Siriporn Maneerat",
    lastResult: "F3 Severe Fibrosis. Follow-up in 3 months.",
  },
  {
    id: "HN-2566-1147",
    name: "Bunmee Somjai",
    nameEn: "Bunmee Somjai",
    age: 55, gender: "M",
    status: "Pending", priority: "Critical",
    date: "2026-06-11 10:55",
    tools: ["SmartLiva", "PICHA"],
    accession: "KKH-US-2026-1122",
    indication: "Suspicious liver mass 3.2 cm, AFP 420 ng/mL",
    ward: "Oncology",
    referrer: "Dr. Thanaporn Wiset",
    lastResult: null,
  },
  {
    id: "HN-2566-4420",
    name: "Wasana Pinthong",
    nameEn: "Wasana Pinthong",
    age: 44, gender: "F",
    status: "Reviewed", priority: "Routine",
    date: "2026-06-09 13:00",
    tools: ["SmartLiva"],
    accession: "KKH-US-2026-1098",
    indication: "Annual liver US, steatosis screening",
    ward: "Health Checkup Centre",
    referrer: "Dr. Nuttapong Chaiyarat",
    lastResult: "F0 No fibrosis. Mild steatosis detected.",
  },
  // PICHA – Digital Pathology
  {
    id: "HN-2566-9341",
    name: "Prayoon Chaidee",
    nameEn: "Prayoon Chaidee",
    age: 58, gender: "M",
    status: "Pending", priority: "Urgent",
    date: "2026-06-11 08:30",
    tools: ["PICHA"],
    accession: "KKH-PATH-2026-0441",
    indication: "Liver biopsy — suspect CCA, OV-endemic background",
    ward: "Hepatobiliary Surgery",
    referrer: "Dr. Wanchai Uttaraphol",
    lastResult: null,
  },
  {
    id: "HN-2566-6622",
    name: "Rattana Kaewsai",
    nameEn: "Rattana Kaewsai",
    age: 49, gender: "F",
    status: "Reviewed", priority: "Routine",
    date: "2026-06-10 14:20",
    tools: ["PICHA"],
    accession: "KKH-PATH-2026-0435",
    indication: "Bile duct biopsy — cholangiopathy workup",
    ward: "GI Oncology",
    referrer: "Dr. Thanaporn Wiset",
    lastResult: "iCCA G2 Stage II. MDT referral recommended.",
  },
  {
    id: "HN-2566-3305",
    name: "Kitti Sirirat",
    nameEn: "Kitti Sirirat",
    age: 63, gender: "M",
    status: "In Progress", priority: "Urgent",
    date: "2026-06-11 09:15",
    tools: ["PICHA"],
    accession: "KKH-PATH-2026-0440",
    indication: "Core needle biopsy — hepatic mass 4.1 cm",
    ward: "Hepatobiliary Surgery",
    referrer: "Dr. Wanchai Uttaraphol",
    lastResult: null,
  },
  // Multi-module
  {
    id: "HN-2566-7112",
    name: "Amnaj Veerasak",
    nameEn: "Amnaj Veerasak",
    age: 71, gender: "M",
    status: "Pending", priority: "Critical",
    date: "2026-06-11 07:50",
    tools: ["AXIA", "SmartLiva"],
    accession: "KKH-MUL-2026-0021",
    indication: "ICU — hepatic encephalopathy + altered consciousness",
    ward: "ICU",
    referrer: "Dr. Pairin Kamolchan",
    lastResult: null,
  },
];

/** Lookup a patient by HN id or demo reference id. Returns null if not found. */
export function getPatientById(id) {
  return (
    MOCK_PATIENTS.find((p) => p.id === id) ??
    DEMO_PATIENTS.find((p) => p.id === id) ??
    null
  );
}